### ISSUE TITLE
double clicking on token row in popover window should trigger the 'select token' action

### ISSUE THREAD

**Issue by qfulsher** [dayvar14/obr-draw-steel#54]
**Is your feature request related to a problem? Please describe.** Not really a problem, but right click > select token is 

**Describe the solution you'd like** 
![image](https://github.com/user-attachments/assets/9a3e42f8-e1fd-411d-a8b3-d751056a8b3e)
double clicking beefcake in this scenario would cause the select token action to trigger. 

**Describe alternatives you've considered** There's a right click > select token, but in a big fight that can be an annoying amount of key strokes. Open to other alternatives though

**Additional context**

**Comment by qfulsher** [comment]
So was reading through the code and if you double click the circular icon, then it does this. Could just wire up a double click handler to call the same method on the row, not just the icon

**Comment by qfulsher** [comment]
or tweak the UI to clue users in that the icons are clickable

**Comment by daniel-ayvar** [comment]
@qfulsher yes. need to work on docs sometime but currently clicking the token works with the same purpose. I agree, double clicking is a fine extra way to select the token. I'll take a look at your pr
