### ISSUE TITLE
Application crashing my scene

### ISSUE THREAD

**Issue by Theosis23** [dayvar14/obr-draw-steel#65]
**Describe the bug** 
Whenever I add application to room, the scene crashes with the message "Could not send message with reason: rate limited". This did not happen immediately but after setting up the encounter and then refreshing the page. But since then any time I delete and re add the application to the room it immediately crashes just that scene with the same error message. When the application is deleted from the room, the scene then loads again.

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/8029a266-56d2-4750-ae0e-c320fa085e3b)

**Desktop (please complete the following information):**

- OS: Windows 10 pro
- Browser Chrome 
- Version 130.0.6723.70 (Chrome)

**Comment by daniel-ayvar** [comment]
Aw yes. This is a big issue. I'll get on it.

**Comment by daniel-ayvar** [comment]
This seems to be a bug when loading a scene a second time. Reloaded causes the tokens to update super frequently, causing the entire scene to get rate limited.

**Comment by daniel-ayvar** [comment]
@Theosis23 apologies. i believe a fix has been released. Can you confirm so I can close this issue?

**Comment by Theosis23** [comment]
Just tested and reloaded. All good! 
Thank you so much!
